services:
  api:
    build:
      context: .
      dockerfile: GestorPedidos.API/Dockerfile
    container_name: gestorpedidos-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=ordercontroldb;Username=postgres;Password=123456

  postgres:
    image: postgres:15
    container_name: ordercontrol-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: ordercontroldb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
